import type { Metadata } from 'next';
import { pageMetadata, OG } from '@/lib/seo';
import Header from '@/components/Header';
import Footer from '@/components/Footer';
import Founders from '@/components/Founders';
import FinalCTA from '@/components/FinalCTA';
import { SITE } from '@/lib/site';
import { FOUNDERS } from '@/lib/founders';

export const metadata: Metadata = pageMetadata({title:'About Us and Our Founders',description:'Meet Walter McCain III and Sebastian Miller, the founders of Signal Harbor. A managed AI visibility program connecting buyer discovery, content, and measurable impact.',path:'/about/',image:OG.company,imageAlt:'Signal Harbor and its founders'});
const PRINCIPLES=[['Evidence sets the direction.','Start with the answers buyers see and the sources behind them. Focus the work on gaps that matter to your business.'],['People make the decisions.','Your team brings the company facts, product knowledge, and final approval. AI and agents help the work move.'],['The work completes the loop.','Research becomes a campaign. Approved content gets published. Remeasurement and connected data inform the next move.']];
const aboutLd={'@context':'https://schema.org','@type':'AboutPage','@id':`${SITE.url}/about/#webpage`,name:'About Signal Harbor and its founders',url:`${SITE.url}/about/`,isPartOf:{'@id':`${SITE.url}/#website`},about:{'@id':`${SITE.url}/#organization`},mainEntity:FOUNDERS.map(f=>({'@type':'Person',name:f.name,image:SITE.url+f.image,jobTitle:'Co-founder',url:`${SITE.url}/about/#${f.id}`,sameAs:[f.linkedin],worksFor:{'@id':`${SITE.url}/#organization`}}))};

export default function AboutPage(){return <><Header/><main>
<section className="hero-light overflow-hidden" aria-labelledby="about-title"><div className="container-x about-story py-12 sm:py-16"><div><p className="eyebrow">About us</p><h1 id="about-title" className="mt-4 text-4xl font-extrabold leading-[1.12] tracking-tight text-navy sm:text-5xl">Good companies should be easier to find.</h1><p className="mt-6 max-w-xl text-lg leading-relaxed text-navy/85">Buyers are asking AI who to trust. We help your company become easier to discover, understand, and choose.</p><p className="mt-4 max-w-xl text-base leading-relaxed text-navy/85">Signal Harbor brings AI search intelligence, prepared marketing work, and a managed team into one connected program for middle-market companies, enterprise teams, and agency partners.</p><a href="#founders" className="harbor-text-link mt-7 inline-flex font-semibold text-harbor underline underline-offset-4">Meet Walter and Sebastian <span aria-hidden="true"> ↘</span></a></div><div className="about-signal harbor-aura"><p className="portal-kicker">The Signal Harbor idea</p><h2>Clarity at every step.</h2><ol>{[['01','Be found.','Understand the questions buyers ask.'],['02','Be understood.','Give AI and buyers a clear, accurate story.'],['03','Be considered.','Turn evidence into content that helps buyers choose.']].map(([n,title,text])=><li key={n}><span aria-hidden="true">{n}</span><div><h3>{title}</h3><p>{text}</p></div></li>)}</ol></div></div></section>
<section className="bg-mist" aria-labelledby="approach-title"><div className="container-x py-12 sm:py-14"><div className="max-w-2xl"><p className="eyebrow">How we work</p><h2 id="approach-title" className="mt-3 text-3xl font-bold tracking-tight text-navy">Built for the team behind the brand.</h2><p className="mt-4 text-base leading-relaxed text-navy/85">Marketing teams need a clear priority and the capacity to act on it. We connect the research, the work, and the measurement while your people stay in control.</p></div><div className="about-principles mt-8">{PRINCIPLES.map(([title,text])=><article key={title}><h3>{title}</h3><p>{text}</p></article>)}</div></div></section>
<Founders/>
<section className="bg-canvas" aria-labelledby="ecosystem-title"><div className="container-x pb-12 sm:pb-16"><div className="about-ecosystem"><div><p className="eyebrow">Our community</p><h2 id="ecosystem-title">Part of Chicago’s startup ecosystem.</h2><p>Building alongside founders, operators, and people bringing new ideas to life.</p></div><ul><li><a href="https://www.luc.edu/leadershiphub/centers/ignitelab/" target="_blank" rel="noopener noreferrer">Loyola University Chicago’s Ignite Lab <span className="sr-only">(opens in a new tab)</span><span aria-hidden="true">↗</span></a><span>Member</span></li><li><a href="https://1871.com/" target="_blank" rel="noopener noreferrer">1871 <span className="sr-only">(opens in a new tab)</span><span aria-hidden="true">↗</span></a><span>Member</span></li></ul></div></div></section>
<FinalCTA/></main><Footer/><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(aboutLd)}}/></>}
